# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
      env: R_COVR=run-covr
    - os: linux
      r: devel
      warnings_are_errors: false
    - os: osx
      r: release

after_success:
  - test $R_COVR && Rscript -e "covr::codecov()"

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
